"""
add_docusaurus_tags.py
Migrates existing `level` and `type` frontmatter fields into Docusaurus's
native `tags` array so they render as clickable chips on each doc page.

Mapping:
  level: beginner     → tags: [level/beginner]
  type: guide         → tags: [..., type/guide]

Existing fields are kept intact — the generator still reads them.
Auto-generated index.md and _intro.md files are skipped.

Usage:
  python add_docusaurus_tags.py           # dry run — prints what would change
  python add_docusaurus_tags.py --apply   # writes changes to disk
"""
import os
import re
import sys

DOCS_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "docs")
)

# Files generated by generate_mermaids.py — never hand-edit them
SKIP_FILES = {"index.md", "_intro.md", "full-sitemap.md"}

# Controlled vocabulary — strip inline comments before matching
LEVEL_MAP = {
    "beginner":     "level/beginner",
    "intermediate": "level/intermediate",
    "advanced":     "level/advanced",
    "expert":       "level/expert",
}

TYPE_MAP = {
    "overview":  "type/overview",
    "guide":     "type/guide",
    "tutorial":  "type/tutorial",
    "reference": "type/reference",
    "resource":  "type/resource",
    "api-doc":   "type/api-doc",
}


def _strip_comment(value: str) -> str:
    """Remove trailing inline YAML comment (# ...)."""
    return value.split("#")[0].strip().strip('"').strip("'")


def extract_field(frontmatter_text: str, field: str) -> str | None:
    """Return the bare value of a top-level scalar field, or None."""
    for line in frontmatter_text.split("\n"):
        stripped = line.strip()
        if stripped.startswith(f"{field}:"):
            raw = stripped[len(f"{field}:"):].strip()
            return _strip_comment(raw) or None
    return None


def build_tags(frontmatter_text: str) -> list[str]:
    """Build the tags list from level + type fields."""
    tags = []
    level_raw = extract_field(frontmatter_text, "level")
    type_raw  = extract_field(frontmatter_text, "type")
    if level_raw and level_raw in LEVEL_MAP:
        tags.append(LEVEL_MAP[level_raw])
    if type_raw and type_raw in TYPE_MAP:
        tags.append(TYPE_MAP[type_raw])
    return tags


def inject_tags(content: str, tags: list[str]) -> str:
    """
    Insert `tags:` block into existing frontmatter, just before the closing `---`.
    Assumes frontmatter is present and well-formed.
    """
    tag_lines = "\n".join(f"  - {t}" for t in tags)
    tags_block = f"tags:\n{tag_lines}"
    # Replace the closing --- with the tags block + closing ---
    return re.sub(
        r'\n---(\s*\n)',
        f"\n{tags_block}\n---\\1",
        content,
        count=1
    )


def process_file(path: str, apply: bool) -> bool:
    """
    Returns True if the file would be (or was) changed.
    """
    with open(path, encoding="utf-8") as f:
        content = f.read()

    if not content.startswith("---"):
        return False

    m = re.match(r'^---\n(.*?)\n---', content, re.DOTALL)
    if not m:
        return False

    frontmatter_text = m.group(1)

    # Skip if tags already exist
    if re.search(r'^\s*tags\s*:', frontmatter_text, re.MULTILINE):
        return False

    tags = build_tags(frontmatter_text)
    if not tags:
        return False

    new_content = inject_tags(content, tags)
    rel = os.path.relpath(path, DOCS_ROOT)

    if apply:
        with open(path, "w", encoding="utf-8") as f:
            f.write(new_content)
        print(f"  ✔  {rel}  →  {tags}")
    else:
        print(f"  ○  {rel}  →  {tags}")

    return True


def main():
    apply = "--apply" in sys.argv
    mode = "APPLYING" if apply else "DRY RUN (pass --apply to write)"
    print(f"\n{'='*60}")
    print(f"add_docusaurus_tags.py — {mode}")
    print(f"Docs root: {DOCS_ROOT}")
    print(f"{'='*60}\n")

    changed = skipped = 0
    for root, dirs, files in os.walk(DOCS_ROOT):
        # Don't descend into hidden dirs
        dirs[:] = [d for d in dirs if not d.startswith(".")]
        for fname in sorted(files):
            if fname in SKIP_FILES or not fname.endswith(".md"):
                continue
            path = os.path.join(root, fname)
            if process_file(path, apply):
                changed += 1
            else:
                skipped += 1

    print(f"\n{'='*60}")
    print(f"{'Changed' if apply else 'Would change'}: {changed} files")
    print(f"Skipped (no mappable fields or tags already present): {skipped} files")
    if not apply:
        print("\nRun with --apply to write changes.")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
